### ISSUE TITLE
The environment variable LD_LIBRARY_PATH is not set

### ISSUE THREAD

**Issue by fegyi001** [schwankner/esa-snap-with-python#5]
I'm new to SNAP, so maybe a rookie question/issue here.

I pulled the Docker image with this:
```bash
docker pull mrmoor/esa-snap-with-python
```

And tried to run it & enter the running container's terminal with this:
```bash
docker run -it mrmoor/esa-snap-with-python:latest bash
```

But this is what I got after that:
```bash
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH is not set. It must contain the current folder '.'.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
java.lang.IllegalStateException: Operator SPI not found for operator [bash]
        at org.esa.snap.core.gpf.annotations.ParameterDescriptorFactory.getOpSpi(ParameterDescriptorFactory.java:262)
        at org.esa.snap.core.gpf.annotations.ParameterDescriptorFactory.createMapBackedOperatorPropertyContainer(ParameterDescriptorFactory.java:67)
        at org.esa.snap.core.gpf.main.CommandLineTool.convertParameterMap(CommandLineTool.java:400)
        at org.esa.snap.core.gpf.main.CommandLineTool.runOperator(CommandLineTool.java:296)
        at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:284)
        at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
        at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
        at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
        at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
        at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
        at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
        at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

Error: Operator SPI not found for operator [bash]
```

Since I'm new to it, and could not find anything either here on Github or on Docker Hub about how to use this image, could you help me with that?

Many thanks!

**Comment by fegyi001** [comment]
Oh, I got it, `bash` is a wrong command since the base image of this (mrmoor/esa-snap) ends with 
```bash
ENTRYPOINT ["/usr/local/snap/bin/gpt"]
```
Therefore I'm already running `gpt`.
